Repository IBM/ibm-monitoring-exporters-operator, pull requests merged in 2020-11, with the labels that each got.

#36 fix scc issue
  README.md
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.4/ibm-monitoring-exporters-operator.v1.9.4.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/exporter/handler/sync.go
  pkg/controller/exporter/model/scc.go
Labels: size/M

#37 use issuer instead of clusterissuer; bump up version
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.5/ibm-monitoring-exporters-operator.v1.9.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.5/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/ibm-monitoring-exporters-operator.package.yaml
  deploy/role.yaml
  pkg/controller/exporter/model/cert.go
  version/version.go
Labels: size/XL

#39 update image digest
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.5/ibm-monitoring-exporters-operator.v1.9.5.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
Labels: size/M

#40 update management ingress image
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.5/ibm-monitoring-exporters-operator.v1.9.5.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#41 use kubernetes.io/arch label
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.5/ibm-monitoring-exporters-operator.v1.9.5.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS
