Repository IBM/ibm-monitoring-exporters-operator, pull requests merged in 2020-05, with the labels that each got.

#10 use image digest in container env; roll back cr status data type changes
  deploy/crds/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/crds/monitoring.operator.ibm.com_v1alpha1_exporter_cr.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/ibm-monitoring-exporters-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/operator.yaml
  pkg/apis/monitoring/v1alpha1/exporter_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/exporter/handler/sync.go
  pkg/controller/exporter/model/collectd.go
  pkg/controller/exporter/model/common.go
  pkg/controller/exporter/model/kubestate.go
  pkg/controller/exporter/model/nodeexporter.go
  pkg/controller/exporter/model/router.go
Labels: size/XL

#11 update productVersion of metering annotation to 3.4.0
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/ibm-monitoring-exporters-operator.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/exporter/model/common.go
Labels: size/XS

#12 update operand image
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/ibm-monitoring-exporters-operator.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/S

#13 update image digest for management ingress and collectd exporter
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/ibm-monitoring-exporters-operator.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#14 update for ibm certificate
  deploy/crds/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/crds/monitoring.operator.ibm.com_v1alpha1_exporter_cr.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.8.0/ibm-monitoring-exporters-operator.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.8.0/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/ibm-monitoring-exporters-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/exporter/model/cert.go
  pkg/controller/exporter/model/collectd.go
  pkg/controller/exporter/model/common.go
  pkg/controller/exporter/model/kubestate.go
  pkg/controller/exporter/model/nodeexporter.go
  pkg/controller/exporter/model/router.go
Labels: size/M

#15 add beta channel
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/ibm-monitoring-exporters-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/ibm-monitoring-exporters-operator.package.yaml
Labels: size/XS

#17 add scripts to protect csv not changed. only dev csv can be changed
  common/scripts/.githooks/pre-commit
  common/scripts/csv-protect.py
  common/scripts/push-csv.sh
Labels: size/L

#16 fix operator2operator upgrade failure because of label selectors
  pkg/controller/exporter/model/collectd.go
  pkg/controller/exporter/model/kubestate.go
  pkg/controller/exporter/model/nodeexporter.go
Labels: size/M

#19 update node exporter default port
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.1/ibm-monitoring-exporters-operator.v1.9.1.clusterserviceversion.yaml
  pkg/controller/exporter/model/nodeexporter.go
  pkg/controller/exporter/model/router.go
Labels: size/S

#20 power needs more memory
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.1/ibm-monitoring-exporters-operator.v1.9.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#18 improve CSV description and readme with template
  README.md
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.1/ibm-monitoring-exporters-operator.v1.9.1.clusterserviceversion.yaml
Labels: lgtm, size/M
