Repository IBM/ibm-monitoring-exporters-operator, pull requests merged in 2020-04, with the labels that each got.

#3 add dependency request
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.8.1/ibm-monitoring-exporters-operator.v1.8.1.clusterserviceversion.yaml
Labels: size/S

#4 fix ibm certification issues
  deploy/crds/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/crds/monitoring.operator.ibm.com_v1alpha1_exporter_cr.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.8.0/ibm-monitoring-exporters-operator.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.8.0/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.8.1/ibm-monitoring-exporters-operator.v1.8.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.8.1/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: size/L

#6 rename csv 1.8.1 to 1.9.0
  Makefile
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/ibm-monitoring-exporters-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/ibm-monitoring-exporters-operator.package.yaml
  version/version.go
Labels: size/S

#7 fix validation issue found by ibm certification
  deploy/crds/monitoring.operator.ibm.com_v1alpha1_exporter_cr.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/ibm-monitoring-exporters-operator.v1.9.0.clusterserviceversion.yaml
Labels: size/XS

#8 remove imagePullSecrets from default CR
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.8.0/ibm-monitoring-exporters-operator.v1.8.0.clusterserviceversion.yaml
Labels: size/XS

#9 remove default imagePullSecret
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.8.0/ibm-monitoring-exporters-operator.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.0/ibm-monitoring-exporters-operator.v1.9.0.clusterserviceversion.yaml
Labels: size/XS
