Repository IBM/ibm-monitoring-exporters-operator, pull requests merged in 2021-03, with the labels that each got.

#52 preserve cert-manager added labels
  pkg/controller/exporter/model/collectd.go
  pkg/controller/exporter/model/common.go
  pkg/controller/exporter/model/kubestate.go
  pkg/controller/exporter/model/nodeexporter.go
Labels: size/M

#53 issue 44463 - update the version of manifest-tool
  Makefile
Labels: size/XS

#54 csv update - added version replace
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.10.1/ibm-monitoring-exporters-operator.v1.10.1.clusterserviceversion.yaml
Labels: lgtm, size/XS

#55 preserve cert-manager added labels
  pkg/controller/exporter/model/collectd.go
  pkg/controller/exporter/model/common.go
  pkg/controller/exporter/model/kubestate.go
  pkg/controller/exporter/model/nodeexporter.go
Labels: size/M
