Repository IBM/ibm-monitoring-exporters-operator, pull requests merged in 2021-06, with the labels that each got.

#65 fix cv linter issue:CSVHasValidRelatedImages
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.11.0/ibm-monitoring-exporters-operator.v1.11.0.clusterserviceversion.yaml
Labels: size/S

#66 add OWNERS file
  OWNERS
Labels: size/XS

#67 Copyright year updated #45123
  Makefile
  pkg/controller/exporter/exporter_controller.go
  version/version.go
Labels: approved, lgtm, size/XS

#68 increment operator version
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.12.0/ibm-monitoring-exporters-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.12.0/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/ibm-monitoring-exporters-operator.package.yaml
  version/version.go
Labels: approved, size/XL

#69 release-cd merge to master
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.12.0/ibm-monitoring-exporters-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.12.0/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/ibm-monitoring-exporters-operator.package.yaml
  version/version.go
Labels: approved, size/XL
