Repository IBM/ibm-monitoring-exporters-operator, pull requests merged in 2021-02, with the labels that each got.

#44 update v3 channel
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.10.0/ibm-monitoring-exporters-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.10.0/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/ibm-monitoring-exporters-operator.package.yaml
  version/version.go
Labels: size/S

#45 fix cve-2021-3121
  go.mod
  go.sum
Labels: size/M

#47 update images except ingress
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.10.0/ibm-monitoring-exporters-operator.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/S

#48 Security issues
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.6/ibm-monitoring-exporters-operator.v1.9.6.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.6/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/ibm-monitoring-exporters-operator.package.yaml
  go.mod
  go.sum
  version/version.go
Labels: size/XL

#50 bump operator version and update icp-management-ingress digest
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.10.1/ibm-monitoring-exporters-operator.v1.10.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.10.1/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/ibm-monitoring-exporters-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XL

#51 Update manifest-tool version
  Makefile
Labels: size/XS
