Repository IBM/ibm-monitoring-exporters-operator, pull requests merged in 2021-04, with the labels that each got.

#58 2.5.11 version of icp-management-ingress digest updated
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.6/ibm-monitoring-exporters-operator.v1.9.6.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#59 refresh ingress digest
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.6/ibm-monitoring-exporters-operator.v1.9.6.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#60 updated images with vascans fixes
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.9.6/ibm-monitoring-exporters-operator.v1.9.6.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: lgtm, size/S

#61 operand auto sha update+bump version
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.11.0/ibm-monitoring-exporters-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/1.11.0/monitoring.operator.ibm.com_exporters_crd.yaml
  deploy/olm-catalog/ibm-monitoring-exporters-operator/ibm-monitoring-exporters-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: lgtm, size/XL
